import { useMemo, useState } from 'react'
import * as d3 from 'd3'
import { ChartFrame, Select } from '@/components/ChartFrame'
import { Legend } from '@/components/Legend'
import type { CensusFile } from '@/lib/types'

const GALLERY_SLUG: Record<string, string> = {
  Scatterplot: 'scatter-plot', Bubble: 'bubble-plot', '2D Density': '2d-density-plot',
  'Connected Scatter': 'connected-scatter-plot', Heatmap: 'heatmap', Correlogram: 'correlogram',
  Boxplot: 'box-plot', Violin: 'violin-plot', Histogram: 'histogram', Density: 'density-plot',
  Ridgeline: 'ridgeline-plot', Beeswarm: 'beeswarm', Barplot: 'barplot', Lollipop: 'lollipop',
  'Line chart': 'line-chart', Timeseries: 'timeseries', 'Area chart': 'area-plot',
  'Stacked Area': 'stacked-area-plot', Donut: 'donut', 'Pie Chart': 'pie-plot', Treemap: 'treemap',
}

/** Which gallery charts this app already implements, by name. */
const BUILT = new Set(['Scatterplot', 'Correlogram', 'Heatmap', 'Boxplot', 'Violin', 'Beeswarm',
  'Ridgeline', 'Timeseries', 'Lollipop', 'Treemap', 'Donut', 'Bubble', 'Histogram',
  'Density', 'Barplot', 'Area chart', '2D Density', 'Line chart', 'Stacked Area', 'Connected Scatter'])

/** Gallery charts built here that the notebooks never drew at all. */
const BEYOND_ESTATE = [
  { chart: 'Ridgeline', tab: 'Distribution', why: 'distribution shift by season/year' },
  { chart: 'Radar', tab: 'Ranking', why: 'per-site chemical fingerprint' },
  { chart: 'Sankey', tab: 'Flow', why: 'filters → EC method → HIPS / season' },
  { chart: 'Streamgraph', tab: 'PMF sources', why: 'source mix as a shape' },
  { chart: 'Bubble map', tab: 'Map', why: 'network geography as a filter' },
]

/**
 * The census page — what the 211 notebooks actually drew, mapped onto the
 * react-graph-gallery taxonomy. Generated by gallery/census/build_census.py.
 */
export function CensusPage({ census }: { census: CensusFile }) {
  const [chart, setChart] = useState(census.by_chart[0]?.[0] ?? '')
  const max = census.by_chart[0]?.[1] ?? 1
  const catColor = useMemo(
    () => d3.scaleOrdinal<string>().domain(census.by_category.map((c) => c[0])).range(d3.schemeTableau10),
    [census.by_category]
  )
  const examples = census.examples[chart] ?? []

  return (
    <>
      <ChartFrame
        title="What the notebooks already draw"
        subtitle={`${census.n_figures} figure-producing cells across ${census.n_notebooks} notebooks, classified by the matplotlib primitives each cell uses and mapped onto the react-graph-gallery taxonomy. Green means this app already has an interactive version.`}
        provenance="generated by gallery/census/build_census.py — re-run it after adding notebooks"
        exportable={false}
      >
        <table className="census-table">
          <thead>
            <tr>
              <th>Gallery chart</th>
              <th style={{ width: '46%' }}>Figures in repo</th>
              <th>Count</th>
              <th>Here</th>
              <th>Reference</th>
            </tr>
          </thead>
          <tbody>
            {census.by_chart.map(([name, n]) => (
              <tr key={name}>
                <td>{name}</td>
                <td><div className="bar" style={{ width: `${(n / max) * 100}%` }} /></td>
                <td className="mono">{n}</td>
                <td>{BUILT.has(name) ? <span className="built">✓ built</span> : <span className="mono">—</span>}</td>
                <td>
                  {GALLERY_SLUG[name] ? (
                    <a href={`https://www.react-graph-gallery.com/${GALLERY_SLUG[name]}`} target="_blank" rel="noreferrer">gallery ↗</a>
                  ) : null}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <Legend items={census.by_category.map(([c, n]) => ({ label: c, color: catColor(c), shape: 'square' as const, detail: String(n) }))} />
      </ChartFrame>

      <ChartFrame
        title="Built here but absent from the estate"
        subtitle="Gallery charts the notebooks never drew — the categories matplotlib makes awkward are exactly where the interactive version earns its place."
        exportable={false}
      >
        <table className="census-table">
          <thead>
            <tr><th>Chart</th><th>Tab</th><th>Question it answers</th></tr>
          </thead>
          <tbody>
            {BEYOND_ESTATE.map((b) => (
              <tr key={b.chart}><td>{b.chart}</td><td className="mono">{b.tab}</td><td>{b.why}</td></tr>
            ))}
          </tbody>
        </table>
      </ChartFrame>

      <ChartFrame
        title="Where each chart type comes from"
        subtitle="Real titles and axis labels lifted from the notebooks, so you can trace any chart in this app back to the analysis it replaces."
        controls={<Select label="chart type" value={chart} options={census.by_chart.map((c) => c[0])} onChange={setChart} />}
        exportable={false}
      >
        {examples.length === 0 ? (
          <p className="frame-empty">No titled examples recorded for this chart type.</p>
        ) : (
          <ul style={{ margin: 0, paddingLeft: 18, fontSize: 13, lineHeight: 1.7 }}>
            {examples.map((e, i) => (
              <li key={i}>
                {e.title}
                {(e.x || e.y) && <span style={{ color: 'var(--ink-muted)' }}> — {e.y || '?'} vs {e.x || '?'}</span>}
                <div style={{ fontSize: 11, color: 'var(--ink-muted)', fontFamily: 'var(--mono)' }}>{e.notebook}</div>
              </li>
            ))}
          </ul>
        )}
      </ChartFrame>

      <ChartFrame title="Heaviest notebooks" subtitle="Where the figures are concentrated." exportable={false}>
        <ol style={{ margin: 0, paddingLeft: 22, fontSize: 12.5, lineHeight: 1.65, fontFamily: 'var(--mono)' }}>
          {census.top_notebooks.map(([nb, n]) => (
            <li key={nb}>
              {nb} <span style={{ color: 'var(--ink-muted)' }}>· {n} figures</span>
            </li>
          ))}
        </ol>
      </ChartFrame>
    </>
  )
}
